[project]
name = "src"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "graphviz>=0.21",
    "joblib>=1.5.2",
    "nltk>=3.9.2",
    "scikit-learn==1.5.1",
    "streamlit>=1.50.0",
]
